Implement get_inclusion_state serialization
iotaledger/entangled pull request #1035
Opened 2019-03-28 08:04 UTC by jkrvivian

- Serialize response
- Deserialize request
- Implement helper function utarray_to_json_boolean_array

Close #871

2019-03-29 05:38 UTC, oopsmonk requested changes

2019-03-29 05:38 UTC, oopsmonk commented on cclient/serialization/json/helpers.c
> +    while ((p = (int*)utarray_next(ut, p))) {
incompatible type assignment.

2019-03-29 05:38 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.c
>    size_t len = 0;
unused variable.

2019-03-29 05:38 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.c
>  retcode_t json_get_inclusion_states_serialize_request(const serializer_t *const s,
please correct the const placement as `type const * const variable`

2019-03-29 05:38 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.h
> +retcode_t json_get_inclusion_states_deserialize_request(const serializer_t* const s, const char* const obj,
const placement.

2019-04-01 05:39 UTC, oopsmonk requested changes

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/tests/get_inclusion_states.c
> +  const char* json_text = "{\"transactions\": [\"" TEST_81_TRYTES_1
const placement.

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/tests/get_inclusion_states.c
> +  const char* json_text = "{\"states\":[true,false]}";
ditto

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/tests/get_inclusion_states.c
>    const char* json_text = "{\"states\": [true,false]}";
ditto

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.c
> +  const char *json_text = NULL;
ditto

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.c
>    const char *json_text = NULL;
ditto

2019-04-01 05:39 UTC, oopsmonk commented on cclient/serialization/json/tests/get_inclusion_states.c
>    const char* json_text =
ditto

2019-04-02 13:45 UTC, oopsmonk requested changes

2019-04-02 13:45 UTC, oopsmonk commented on cclient/serialization/json/get_inclusion_states.c
> +  ret = json_array_to_hash243_queue(json_obj, "tips", &req->tips);
`tips` is optional, please check via `cJSON_HasObjectItem`

2019-04-02 13:45 UTC, oopsmonk commented on cclient/serialization/json/tests/get_inclusion_states.c
> +void test_get_inclusion_states_serialize_request(void) {
please add test cases with no `tips`

2019-04-08 11:05 UTC, thibault-martinez commented
Hi @jkrvivian , could you check Sam's latest comments ? I'm going to need this serialization soon :) Thanks in advance !

2019-04-08 14:12 UTC, jkrvivian commented
Sorry for late update, I've modified it and pushed it!

2019-04-09 02:52 UTC, oopsmonk approved these changes

2019-04-09 03:11 UTC, merged

2019-04-09 03:11 UTC, oopsmonk commented
appreciate your help