common: bundle_transactions_bundle_hash, flex_trit_print
iotaledger/entangled pull request #1207
Opened 2019-05-24 09:59 UTC by oopsmonk

For a better user experience, this PR implements:
* `bundle_transactions_bundle_hash`: fetch bundle hash.
* `flex_trit_print`: print flex_trit vai stdout.

# Test Plan:
CI pass

2019-05-26 12:39 UTC, tsvisabo requested changes
Can you also replace current hash retrieval with calling this function?

2019-05-27 02:37 UTC, oopsmonk commented
These methods are not used in cclient library but in user applications.
I will apply `flex_trit_print` to `transaction_obj_dump` that will enhance its readability.

2019-06-02 11:24 UTC, tsvisabo approved these changes

2019-06-02 11:24 UTC, tsvisabo commented on common/trinary/flex_trit.c
> +
Thanks :)

2019-06-02 13:14 UTC, merged