Create SECURITY.md
iotaledger/entangled pull request #1241
Opened 2019-05-31 18:23 UTC by thibault-martinez

2019-05-31 19:03 UTC, tsvisabo requested changes

2019-05-31 19:03 UTC, tsvisabo commented on SECURITY.md
> +	<li>We ask that you do not to disclosure the problem to third parties until it has been resolved.</li>
do not disclose

2019-05-31 19:03 UTC, tsvisabo commented on SECURITY.md
> +	<li>Out of concern for the availability of our services to all users, please do not attempt to carry out DoS attacks, leverage black hat SEO techniques, spam people, and do other similarly questiona
`and do other similarly questionable things` -> or any other mischief (follow the golden rule)

2019-06-01 15:20 UTC, rajivshah3 commented on SECURITY.md
> +	<li>Do not read, modify or delete data that isn't you own.</li>
```suggestion
	<li>Do not read, modify or delete data that isn't your own.</li>
```

2019-06-02 13:53 UTC, tsvisabo approved these changes

2019-06-02 18:26 UTC, closed without merging