CClient: examples for APIs.
iotaledger/entangled pull request #1253
Opened 2019-06-04 15:22 UTC by oopsmonk

This PR:
* adding API examples
* fixing warnings in CClient

2019-06-05 14:10 UTC, thibault-martinez requested changes

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/exmaple_send_data.c
> +/*
Typo in the file name

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/extended/prepare_transfers.c
>          log_error(client_extended_logger_id, "balance is not match\n");
```suggestion
         log_error(client_extended_logger_id, "balance does not match\n");
```

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/BUILD
> +    name = "cclient_exmaples",
Typo

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_find_transaction_objects.c
> +             transaction_current_index(tx1), transaction_last_index(tx1));
Warning: `cclient/api/examples/example_find_transaction_objects.c:55:67: warning: format specifies type 'unsigned long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]`

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_get_account_data.c
> +    printf("total balance: %zu\n", account.balance);
Warning: `cclient/api/examples/example_get_account_data.c:39:36: warning: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]`

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/extended/prepare_transfers.c
> +    for (size_t i = 0; i < (size_t)(msg_chunks * NUM_TRYTES_MESSAGE); i += NUM_TRYTES_MESSAGE) {
Maybe `msg_chunks` should be `size_t` and not `int` instead of casting here ?

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_travers_bundle.c
> +/*
traverse

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_travers_bundle.c
> +void example_travers_bundle(iota_client_service_t *s) {
traverse

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_get_transaction_to_approve.c
> +/*
get_transactions_to_approve

2019-06-05 14:10 UTC, thibault-martinez commented on cclient/api/examples/example_get_transaction_to_approve.c
> +void example_get_transaction_to_approve(iota_client_service_t *s) {
get_transactions_to_approve

2019-06-06 02:42 UTC, oopsmonk commented on cclient/api/examples/example_find_transaction_objects.c
> +             transaction_current_index(tx1), transaction_last_index(tx1));
interesting, my compiler doesn't complain about it. what's your version?

2019-06-06 06:27 UTC, thibault-martinez commented on cclient/api/examples/example_find_transaction_objects.c
> +             transaction_current_index(tx1), transaction_last_index(tx1));
clang-1001.0.46.4!

2019-06-06 06:48 UTC, thibault-martinez approved these changes

2019-06-06 06:57 UTC, merged