ciri: were_addresses_spent_from api
iotaledger/entangled pull request #1307
Opened 2019-06-19 14:45 UTC by thibault-martinez

Fixes #437

2019-06-21 11:08 UTC, oopsmonk requested changes

2019-06-21 11:08 UTC, oopsmonk commented on ciri/api/tests/test_were_addresses_spent_from.c
> + * Copyright (c) 2018 IOTA Stiftung
```suggestion
 * Copyright (c) 2019 IOTA Stiftung
```

2019-06-21 11:08 UTC, oopsmonk commented on ciri/api/tests/test_were_addresses_spent_from.c
> +//
remove

2019-06-21 14:02 UTC, thibault-martinez commented on ciri/api/tests/test_were_addresses_spent_from.c
> +//
Done

2019-06-23 15:25 UTC, oopsmonk approved these changes

2019-06-23 15:25 UTC, merged