consensus/cw_calculator: add as approvers txs which has approvees pre…
iotaledger/entangled pull request #1346
Opened 2019-07-17 14:50 UTC by tsvisabo

2019-07-17 14:50 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +  iota_stor_pack_t apprvoers_pack;
Typo

2019-07-18 11:58 UTC, thibault-martinez requested changes

2019-07-18 11:58 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +        if (transaction_trunk(&tx) == transaction_branch(&tx)) {
Use `memcmp`

2019-07-18 11:58 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +        ERR_BIND_GOTO(iota_tangle_transaction_find(tangle, NULL, NULL, NULL, approvees, &approvees_pack), ret, done);
This one was created for the API call `findTransactions` and is *really* slow, I'm not sure if we should use it in CW.

2019-07-18 12:06 UTC, tsvisabo commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +        if (transaction_trunk(&tx) == transaction_branch(&tx)) {
whoops

2019-07-18 12:07 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +        if (transaction_trunk(&tx) == transaction_branch(&tx)) {
C++ habits :trollface:

2019-07-20 16:43 UTC, thibault-martinez requested changes

2019-07-20 16:43 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +  DECLARE_PACK_SINGLE_TX(tx, tx_ptr, transaction_pack);
Declare at the top

2019-07-20 16:43 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +  *subtangle_size = 0;
Already done line 41

2019-07-20 16:43 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +          HASH_SET_ITER(approvees, iter, tmp) {
Do we really need to have the overhead of a set for only two approvees ? Can't we just do two `exist` ?

2019-07-20 16:58 UTC, thibault-martinez submitted a review, later dismissed

2019-07-20 16:58 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +  bool trunk_exist;
```suggestion
  bool trunk_exist = false;
```

2019-07-20 16:58 UTC, thibault-martinez commented on ciri/consensus/tip_selection/cw_rating_calculator/cw_rating_dfs_impl.c
> +  bool branch_exist;
```suggestion
  bool branch_exist = false;
```

2019-07-20 17:01 UTC, thibault-martinez approved these changes

2019-07-20 17:12 UTC, merged