WORKSPACE: latest toolchains
iotaledger/entangled pull request #1395
Opened 2019-08-07 13:51 UTC by tsvisabo

2019-08-07 13:52 UTC, thibault-martinez approved these changes

2019-08-13 15:38 UTC, thibault-martinez requested changes
`251dd5b25e04f7bf98f855f8d676cce3c1ddbfff` seems to refer to https://github.com/iotaledger/toolchains but the remote here is https://github.com/th0br0/bazel-toolchains ?

2019-08-20 09:48 UTC, oopsmonk approved these changes

2019-08-20 13:36 UTC, thibault-martinez approved these changes

2019-08-20 13:37 UTC, merged