storage: mariadb impls
iotaledger/entangled pull request #1408
Opened 2019-08-22 15:59 UTC by thibault-martinez

2019-08-28 11:52 UTC, tsvisabo requested changes

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/wrappers.c
> +    return RC_STORAGE_FAILED_PREPARED_STATEMENT;
should be different error here

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/wrappers.c
> +    for (; i >= 0 && ((flex_trit_t*)data)[i] == FLEX_TRIT_NULL_VALUE; --i) {
TODO?

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/storage.c
> +  bind[0].buffer = (char*)count;
this and the previous has almost the same body, can you share their code?

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/storage.c
> +  if (mysql_stmt_bind_result(mariadb_statement, bind_out) != 0) {
can you group both `mysql_stmt_bind_result` `mysql_stmt_store_result` into a *bind_and_store function?

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/storage.c
> +  if (mysql_stmt_bind_param(mariadb_statement, bind) != 0) {
can you group both calls into *bind_and_execute ?

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/storage.c
> +  uint64_t ts = current_timestamp_ms();
you can define in the schema file to set to current timestamp instead

2019-08-28 11:52 UTC, tsvisabo commented on common/storage/sql/mariadb/storage.c
> +
can you merge all 3 update functions?

2019-08-28 19:44 UTC, thibault-martinez commented on common/storage/sql/mariadb/storage.c
> +
Not sure what you mean by that, but we can't factorize more due to the type of the parameter

2019-08-28 19:45 UTC, thibault-martinez commented on common/storage/sql/mariadb/wrappers.c
> +    for (; i >= 0 && ((flex_trit_t*)data)[i] == FLEX_TRIT_NULL_VALUE; --i) {
No, the loop is empty just counting the number of ending 9s

2019-08-28 19:56 UTC, thibault-martinez commented on common/storage/sql/mariadb/storage.c
> +  uint64_t ts = current_timestamp_ms();
It was already like that for SQLite3 so I'd need to change the SQL request and sqlite3 storage to make it in the schema

2019-08-29 05:45 UTC, tsvisabo submitted a review, later dismissed

2019-09-03 12:26 UTC, closed without merging