infra: CMake macOS clean and gitignore
iotaledger/entangled pull request #1419
Opened 2019-08-30 16:00 UTC by thibault-martinez

2019-08-31 03:42 UTC, oopsmonk requested changes

2019-08-31 03:42 UTC, oopsmonk commented on .gitignore
> +utils/containers/hash/hash27*
```suggestion
utils/containers/hash/hash[0-9]*
```

2019-09-01 23:30 UTC, thibault-martinez commented on .gitignore
> +utils/containers/hash/hash27*
Thanks!

2019-09-02 01:26 UTC, oopsmonk approved these changes

2019-09-02 01:26 UTC, merged