entangled/ciri: http_destroy - double free
iotaledger/entangled pull request #1421
Opened 2019-09-01 11:47 UTC by tsvisabo

Fixes #1420

2019-09-01 23:15 UTC, thibault-martinez requested changes
How did you come to the conclusion the segmentation fault was due to this ? I don't see a double free here, where would be the other free ? Removing this would cause a leak ?

2019-09-02 13:01 UTC, tsvisabo commented on ciri/api/http/http.c
> -    free(tangle_iter);
@thibault-martinez 
let's avoid commenting on PRs because github won't allow to comment back,
so, the way `utarray` is implemented, it stores all its element inside one memory block
namely, the field `d`, when we call `utarray_free` regardless of whether we defined a DTOR, this `d` field is freed,
also, when you call `utarray_back`, an offset of the `d` block is being returned, and you free that one two, so this is how we got a double free,

hope this makes it clear

2019-09-02 14:12 UTC, thibault-martinez requested changes

2019-09-02 14:12 UTC, thibault-martinez commented on ciri/api/http/http.c
> +UT_icd ut_spent_addresses_provider_icd = {sizeof(spent_addresses_provider_t), NULL, NULL, NULL};
Can you make them static ?

2019-09-02 14:15 UTC, thibault-martinez commented on ciri/api/http/http.c
> -    free(tangle_iter);
Thanks!

2019-09-03 13:58 UTC, thibault-martinez approved these changes

2019-09-03 14:19 UTC, merged