utils/bundle_miner: read progress of mining as ratio 0-1
iotaledger/entangled pull request #1457
Opened 2019-12-10 10:22 UTC by tsvisabo

- Allow reading the progress of the bundle mining
- Problem is that we can get `1` (progress is done) while some threads work is continued because they 
  are not aware of other thread success

2019-12-16 04:53 UTC, oopsmonk submitted a review, later dismissed

2019-12-24 02:09 UTC, rajivshah3 commented on mobile/ios/Interface.mm
> +    bool found_optimal_index = false;
This seems like it was added to `iota_ios_pow_bundle` instead of `bundle_miner_mine`

2020-01-06 09:16 UTC, oopsmonk requested changes

2020-01-06 09:16 UTC, oopsmonk commented on mobile/ios/Interface.mm
> +
remove

2020-01-08 19:13 UTC, rajivshah3 commented on mobile/android/Interface.cpp
> +
Should this be commented out for now?

2020-01-09 11:22 UTC, oopsmonk approved these changes

2020-01-19 05:11 UTC, merged