Remove recursion from merkle.c
iotaledger/entangled pull request #176
Opened 2018-08-21 19:49 UTC by HowJMay

Remove the recursion in merkle tree in merkle.c

<<Describe the changes>>
mam/v1/merkle.c
# Test Plan:
use test_merkle.c in mam/v1/tests

2018-08-22 01:18 UTC, jserv commented on mam/v1/merkle.c
> +
Avoid such non-functioned change.

2018-08-22 04:42 UTC, HowJMay commented on mam/v1/merkle.c
> +
thanks. I fixed it

2018-08-22 15:58 UTC, jserv commented on mam/v1/merkle.c
> -
Don't change this line.

2018-08-22 16:03 UTC, jserv commented on mam/v1/merkle.c
> +  int tree_depth_width = 1 << depth;
`tree_depth_width` might not be a meaningful name. Can you improve it?

2018-08-22 17:48 UTC, jserv commented
The commit messages should mention the following:
1. performance gain after switching to iteration-based implementation;
2. memory reduction ration because of no extra stack allocation;

Please use `git rebase -i` to rework message(s).

2018-08-26 14:21 UTC, jserv commented
It would be explicit to change subject to `Remove recursion in merkle tree implementation".

2018-08-30 11:20 UTC, HowJMay commented
@thibault-martinez ?

2018-08-30 12:18 UTC, thibault-martinez commented
Hi @HowJMay, thanks for this PR, I'll review it ASAP.
Great perf analysis by the way !

2018-08-31 01:34 UTC, HowJMay commented
thank you><

2018-10-20 02:05 UTC, HowJMay commented
@thibault-martinez Hi! 
It has been a long time since I sent this PR.
I wonder the status of code review of this PR.
I really hope that my PR can be merged into this porject. Thanks !

2018-10-22 07:18 UTC, thibault-martinez commented
Hi @HowJMay , could you solve conflicts on this one please ?

2018-10-22 07:28 UTC, thibault-martinez commented
Hi @HowJMay , could you solve conflict on this please ?

2018-10-22 07:29 UTC, thibault-martinez commented
Hi @HowJMay , could you solve conflict on this please ?

2018-10-22 07:37 UTC, thibault-martinez commented
Hi @HowJMay , could you solve conflict on this PR please ?

2018-10-22 10:00 UTC, thibault-martinez commented
Sorry if you received my comment multiple times, GitHub is having difficulties today.
Your implementation of `merkle_node_index_traverse` gives wrong results for two reasons.
I'll point them out in the review with some other little things.

2018-10-22 10:46 UTC, thibault-martinez requested changes

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
>  static size_t merkle_node_index_traverse(size_t const acc, size_t const depth,
You are not using `acc` at all.

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
>  static size_t merkle_node_index_traverse(size_t const acc, size_t const depth,
You are not using `acc` at all.

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
> +  int width_of_leaves_divide_scale = 1;
You don't need this variable, just use `depth_cursor`.

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
> +  int index = 0;
Initialize it at `depth + acc` instead of adding `depth` at the end.

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
> +      index += ((1 << (depth + 1)) - 1);
You are always adding the same tree here

2018-10-22 10:46 UTC, thibault-martinez commented on mam/v1/merkle.c
> +    if (width_cursor >= (width_of_leaves >> width_of_leaves_divide_scale)) {
Instead of shifting `1` to the left then to the right, just shift `1` to the left of `depth - depth_cursor`

2018-10-27 03:47 UTC, HowJMay commented
I am really sorry for that I did some really stupid error in the last version. 
I have fixed them out. Now, it can run successfully.

2018-10-28 11:24 UTC, thibault-martinez commented
No worries, that's what reviews are for.
Just some final nits and it'll be good to merge.
Please solve conflicts as well.

2018-10-28 11:27 UTC, thibault-martinez requested changes

2018-10-28 11:27 UTC, thibault-martinez commented on mam/v1/merkle.c
> +  int width_of_leaves = 1 << depth;
Use `size_t` for these variables.

2018-10-28 11:27 UTC, thibault-martinez commented on mam/v1/merkle.c
> +  if (!tree_depth) return 0;
Put braces around the `if`

2018-11-03 10:37 UTC, thibault-martinez approved these changes

2018-11-03 10:52 UTC, thibault-martinez commented
@HowJMay ,
Thank you for this really great PR !
Please rebase to develop and it'll be good to merge.

2018-11-03 17:04 UTC, HowJMay commented
thank you for reviewing :)

2018-11-03 17:34 UTC, jserv commented
@HowJMay, Don't use `git merge`. Instead, use `git rebase`: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

2018-11-04 11:23 UTC, thibault-martinez requested changes

2018-11-04 11:23 UTC, thibault-martinez commented on utils/merkle.c
> -
Can you bring back the copyright ?

2018-11-04 11:23 UTC, thibault-martinez commented on utils/merkle.c
> +#include "mam/v1/merkle.h"
Wrong path

2018-11-04 11:23 UTC, thibault-martinez commented on utils/merkle.c
> +static trit_t const merkle_null_hash[HASH_LENGTH] = {0};
`HASH_LENGTH` does not exist

2018-11-06 10:52 UTC, HowJMay commented on utils/merkle.c
> +static trit_t const merkle_null_hash[HASH_LENGTH] = {0};
OK I will fix them this weekend sorry

2018-11-10 18:20 UTC, thibault-martinez approved these changes

2018-11-11 12:16 UTC, merged

2018-11-11 12:17 UTC, thibault-martinez commented
@HowJMay Thanks again for this great PR !