Usage and command line arguments
iotaledger/entangled pull request #212
Opened 2018-08-29 15:36 UTC by thibault-martinez

Fixes #191 

# Test Plan:
Not applicable

2018-08-29 16:07 UTC, tsvisabo requested changes

2018-08-29 16:07 UTC, tsvisabo commented on ciri/conf/conf.c
> +  conf->remote_limite_api = CONF_DEFAULT_REMOTE_LIMIT_API;
typo

2018-08-29 16:07 UTC, tsvisabo commented on ciri/main.c
> +  log_info(MAIN_LOGGER_ID, "Parsing command lien arguments\n");
typo

2018-08-29 16:07 UTC, tsvisabo commented on ciri/conf/conf_provider_getopt.c
> +        return RC_CONF_INVALID_ARGUMENTS;
RC_CIRI_CONF_INVALID_ARGUMENTS

2018-08-29 16:07 UTC, tsvisabo commented on ciri/conf/conf_args.h
> +  ciri_arg_requirement_t status;
should be requirement rather than status i think

2018-08-29 16:07 UTC, tsvisabo commented on ciri/conf/usage.h
> +     "Limit the number of max accepted peers. Default is set to 0 (mutual "
Limits

2018-08-29 16:42 UTC, thibault-martinez commented on ciri/main.c
> +  log_info(MAIN_LOGGER_ID, "Parsing command lien arguments\n");
You're reviewing an old commit, that's fixed

2018-08-29 16:44 UTC, thibault-martinez commented on ciri/conf/conf_args.h
> +  ciri_arg_requirement_t status;
Old commit, it's now `has_arg` to match getop struct field `has_arg`

2018-08-30 06:42 UTC, tsvisabo approved these changes

2018-08-30 06:45 UTC, merged