cclient: implement iota_api_get_inclusion_states
iotaledger/entangled pull request #221
Opened 2018-09-02 20:00 UTC by chenwei-tw

Implement the API `getInclusionStates`, close #46 

A function is implemented to convert json boolean array to utarray. Hence, a boolean type is introduced.

# Test Plan:
CI must pass

2018-09-03 01:32 UTC, oopsmonk commented on cclient/response/get_inclusion_state.h
> +  UT_array* bitmap;
please rename `bitmap` to `states`.

2018-09-03 02:03 UTC, oopsmonk commented on cclient/serialization/json/json_serializer.c
> +      utarray_push_back(ut, &current_obj->type);
1. `type` is a bit-flag. 
2. please check object type, if not boolean return `RC_CCLIENT_JSON_PARSE` in advance.

2018-09-03 02:06 UTC, oopsmonk commented on cclient/serialization/tests/test_json.c
> +  TEST_ASSERT_TRUE(get_inclusion_state_res_bool_at(deserialize_get_is, 0));
please add a `False` case, since boolean has 2 status.

2018-09-03 02:59 UTC, oopsmonk commented on cclient/request/get_inclusion_state.c
> +#include "get_inclusion_state.h"
please add the full standard copyright. see `add_neighbors.c`

2018-09-03 03:00 UTC, oopsmonk commented on cclient/response/get_inclusion_state.c
> +#include "get_inclusion_state.h"
please add the full standard copyright. see `add_neighbors.c`

2018-09-03 07:29 UTC, thibault-martinez requested changes

2018-09-03 07:29 UTC, thibault-martinez commented on cclient/request/get_inclusion_state.c
> +      (get_inclusion_state_req_t*)malloc(sizeof(get_inclusion_state_req_t));
Return `NULL` if malloc fail

2018-09-03 07:29 UTC, thibault-martinez commented on cclient/response/get_inclusion_state.c
> +      (get_inclusion_state_res_t*)malloc(sizeof(get_inclusion_state_res_t));
Return `NULL` if malloc fail

2018-09-03 12:52 UTC, chenwei-tw commented
@thibault-martinez @oopsmonk thanks for review! Unfortunately, I am not free in these days. I will start to fix the code after this Saturday, sorry about that.

2018-09-05 07:43 UTC, thibault-martinez requested changes

2018-09-05 07:43 UTC, thibault-martinez commented on cclient/request/get_inclusion_state.c
> + */
Duplicate copyright

2018-09-05 09:18 UTC, thibault-martinez requested changes

2018-09-05 09:18 UTC, thibault-martinez commented on cclient/serialization/json/json_serializer.c
> +  return ret;
Little code duplication, can we call the label `done` and remove one of the duplicates ?

2018-09-05 12:28 UTC, thibault-martinez approved these changes

2018-09-06 03:21 UTC, merged

2018-09-06 03:22 UTC, oopsmonk commented
thanks @chenwei-tw