cclient: added extended API header file.
iotaledger/entangled pull request #270
Opened 2018-09-11 13:25 UTC by oopsmonk

This PR reviews extended API design in cclient, those extended API functions refer to the [iota/core](https://github.com/iotaledger/iota.js/tree/next/packages/core) in `iota.js`.
`TODO` objects and object operations should be designed and implemented during the API implementation.

# Test Plan:
No

2018-09-11 18:29 UTC, tsvisabo requested changes

2018-09-11 18:29 UTC, tsvisabo commented on cclient/iota_extended_api.h
> +  int32_t keyIndex;
snake_case

2018-09-12 13:55 UTC, tsvisabo requested changes

2018-09-12 13:55 UTC, tsvisabo commented on cclient/iota_extended_api.h
> +typedef UT_array transaction_list_t;
that definitions are useful for other cases, can you have them in `common`?

2018-09-12 15:00 UTC, oopsmonk commented on cclient/iota_extended_api.h
> +typedef UT_array transaction_list_t;
it's in the plan, most of those objects should be in the `common`.  :wink:

2018-09-17 07:03 UTC, thibault-martinez commented
A general comment about the naming of these functions.
Maybe we want to reserve the `iota_api_*` scope for the actual cIRI API ?
What about `iota_client_*` ?

2018-09-17 07:46 UTC, oopsmonk commented
> A general comment about the naming of these functions.
> Maybe we want to reserve the `iota_api_*` scope for the actual cIRI API ?
> What about `iota_client_*` ?

`iota_client_*` sounds good for cclient, but how about  `iota_iri_*` for cIRI since `com.iota.iri.*` packages in IRI?

2018-10-10 19:50 UTC, th0br0 approved these changes

2018-10-10 19:50 UTC, th0br0 commented on cclient/iota_extended_api.h
> +//---------END of TODO objects-------------
Can we get rid of the TODO here?

2018-10-10 19:51 UTC, th0br0 commented
We could also just just not have a `iota_` prefix? :thinking:

2018-10-11 06:26 UTC, thibault-martinez commented
We definitely need to have a naming convention discussion :)

2018-10-11 08:24 UTC, oopsmonk commented
> We could also just just not have a `iota_` prefix? thinking

do you mean both of file name and API functions?

2018-10-11 08:48 UTC, tsvisabo approved these changes

2018-10-19 11:17 UTC, merged