Snapshot WIP
iotaledger/entangled pull request #275
Opened 2018-09-12 14:18 UTC by thibault-martinez

# Test Plan:
WIP

2018-09-13 06:21 UTC, tsvisabo requested changes

2018-09-13 06:21 UTC, tsvisabo commented on common/trinary/tryte_ascii.c
> +    if (dec > 255) {
can not happen if input is `char*`

2018-09-13 06:21 UTC, tsvisabo commented on common/trinary/tryte_ascii.h
> +bool ascii_to_trytes(char const *const input, tryte_t *const output);
should we not have the reverse function as well?

2018-09-13 06:21 UTC, tsvisabo commented on consensus/snapshot/snapshot.c
> +      memcpy(entry->hash, line, 81);  // TODO
that's in case we expect tryte formatted snapshot file

2018-09-13 06:21 UTC, tsvisabo commented on consensus/snapshot/snapshot.c
> +  index = snapshot->index;
Maybe we should use atomic for that?

2018-09-13 06:21 UTC, tsvisabo commented on consensus/snapshot/snapshot.c
> +  rw_lock_handle_rdlock(&snapshot->rw_lock);
what if address was not found in `state_map`?
let's return `retcode_t`

2018-09-13 06:27 UTC, thibault-martinez commented on common/trinary/tryte_ascii.c
> +    if (dec > 255) {
Right

2018-09-13 06:27 UTC, thibault-martinez commented on common/trinary/tryte_ascii.h
> +bool ascii_to_trytes(char const *const input, tryte_t *const output);
Will do

2018-09-13 06:27 UTC, thibault-martinez commented on consensus/snapshot/snapshot.c
> +      memcpy(entry->hash, line, 81);  // TODO
You are reviewing an old commit, this has changed a little but I still expect trytes.
Can it not be trytes ?

2018-09-13 06:29 UTC, thibault-martinez commented on consensus/snapshot/snapshot.c
> +  index = snapshot->index;
Why not, we have an opened issue concerning atomic handles.
In the meantime, this lock has other purposes and it's in reading mode for this.

2018-09-13 06:30 UTC, tsvisabo commented on consensus/snapshot/snapshot.c
> +      memcpy(entry->hash, line, 81);  // TODO
for now only trytes, but i guess we can serialize 4/5 trits per byte in the future
FLEX_TRITS_NUM_243 ?

2018-09-13 06:30 UTC, thibault-martinez commented on consensus/snapshot/snapshot.c
> +  rw_lock_handle_rdlock(&snapshot->rw_lock);
Sure

2018-09-13 06:36 UTC, thibault-martinez commented on consensus/snapshot/snapshot.c
> +      memcpy(entry->hash, line, 81);  // TODO
Already done in the latest commit ;)

2018-09-13 12:58 UTC, tsvisabo approved these changes

2018-09-14 15:59 UTC, tsvisabo approved these changes

2018-09-14 16:00 UTC, merged