cIRI README file
iotaledger/entangled pull request #324
Opened 2018-10-01 11:49 UTC by thibault-martinez

This PR adds a README file for cIRI, fixes #149

2018-10-01 11:54 UTC, th0br0 requested changes

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +A low level implementation of a IOTA node in C.
`an IOTA node`

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +This is a full-featured [IOTA](https://iota.org/) node with a convenient JSON-REST HTTP interface. It allows users to become part of the [IOTA](https://iota.org/) network as both a transaction relay
That's not really the case today? Let's call it WIP node?

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +It is specially designed for users seeking a fast, efficient and fully-compatible network setup.
compatible with what?

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +Running an IRI node also allows light wallet users a node to directly connect to for their own wallet transactions.
let's remove this for now

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +cIRI is built and ran through [bazel](https://www.bazel.build/).
`and run`

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +$ bazel run -- ciri
`bazel run -- ciri <optional flags>`

2018-10-01 11:54 UTC, th0br0 commented on ciri/README.md
> +TODO
let's rather link to some parent tracking issue at the top of this readme instead of having to update this document regularly?

2018-10-01 11:56 UTC, tsvisabo requested changes

2018-10-01 11:56 UTC, tsvisabo commented on ciri/README.md
> +Running an IRI node also allows light wallet users a node to directly connect to for their own wallet transactions.
`allows light wallet users a node to directly connect to for` ->
`allows light wallet users to have a node with whom they can directly connect to for`

2018-10-01 13:23 UTC, tsvisabo requested changes

2018-10-01 13:23 UTC, tsvisabo commented on ciri/README.md
> +$ bazel run -- ciri <optional flags>
This should also contain a table for more detailed configuration usage

2018-10-02 08:39 UTC, th0br0 approved these changes

2018-10-02 08:39 UTC, th0br0 commented on ciri/README.md
> +$ bazel run -- ciri <optional flags>
It does, see below

2018-10-02 12:49 UTC, tsvisabo approved these changes

2018-10-02 13:08 UTC, merged