cppclient - check for more null cases and return optional in getNodeInfo
iotaledger/entangled pull request #36
Opened 2018-07-01 12:34 UTC by tsvisabo

Return optional on getNodeInfo
treat other null cases

2018-07-01 12:36 UTC, th0br0 requested changes

2018-07-01 12:36 UTC, th0br0 commented on cppclient/api_json.cc
> +  auto niOptional = getNodeInfo();
let's call these `maybeNodeInfo`?

2018-07-01 12:36 UTC, th0br0 commented on cppclient/api_json.cc
> +    return {};
this should return `false` explicitly

2018-07-01 13:42 UTC, tsvisabo commented on cppclient/api_json.cc
> +    return {};
definitley

2018-07-01 13:42 UTC, tsvisabo commented on cppclient/api_json.cc
> +  auto niOptional = getNodeInfo();
maybe :)

2018-07-02 06:47 UTC, th0br0 approved these changes

2018-07-02 06:48 UTC, th0br0 commented
Rebase on master please

2018-07-03 07:31 UTC, merged