utils/hash_structs - hash_set_for_each
iotaledger/entangled pull request #395
Opened 2018-10-14 12:18 UTC by tsvisabo

2018-10-14 15:25 UTC, th0br0 commented on utils/hash_containers.c
> +  hash_set_entry_t *curr_entry = NULL;
As we call a `bitset` a `bitset`, we should probably call this `hashset` as well? (just a side remark)

2018-10-14 15:26 UTC, th0br0 requested changes

2018-10-14 15:26 UTC, th0br0 commented on utils/hash_containers.c
> +    if ((ret = func(container, curr_entry->hash))) {
This makes the implicit assumption that `RC_OK == 0`.

2018-10-15 06:38 UTC, tsvisabo commented on utils/hash_containers.c
> +    if ((ret = func(container, curr_entry->hash))) {
yeah, we can try to explicitly use `RC_OK`, should be enforced anywhere though

2018-10-15 08:22 UTC, tsvisabo commented on utils/hash_containers.c
> +  hash_set_entry_t *curr_entry = NULL;
Sounds good for set, but then we have hashqueue,hashlist,hashdll (hashdoublelinkedlist?)

2018-10-15 08:50 UTC, th0br0 approved these changes

2018-10-15 13:12 UTC, merged