api: gTTA implementation (WIP)
iotaledger/entangled pull request #447
Opened 2018-10-26 14:39 UTC by thibault-martinez

Current tests are covering failure cases.
Still need to ass an extensive test on success gTTA.

# Test Plan:
Added test

2018-10-28 11:54 UTC, tsvisabo approved these changes

2018-11-02 14:04 UTC, th0br0 requested changes
Fix conflicts as well?

2018-11-02 14:04 UTC, th0br0 commented on cclient/response/get_transactions_to_approve.c
> +    res->branch = trit_array_new(HASH_LENGTH_TRIT);
branch & trunk are only 1 trit long, shouldn't these be fixed size `flex_trit_t` arrays?

2018-11-02 14:04 UTC, th0br0 commented on ciri/api/api.c
> +bool invalid_subtangle_status(iota_api_t const *const api) {
make this `static`

2018-11-02 14:09 UTC, thibault-martinez commented on cclient/response/get_transactions_to_approve.c
> +    res->branch = trit_array_new(HASH_LENGTH_TRIT);
I wanted to do that, but it as a lot of implications in the serialization; and I think @oopsmonk already has an issue regarding this.

2018-11-02 14:09 UTC, th0br0 commented on cclient/response/get_transactions_to_approve.c
> +    res->branch = trit_array_new(HASH_LENGTH_TRIT);
Fair enough

2018-12-17 11:37 UTC, tsvisabo approved these changes

2018-12-17 11:48 UTC, jserv commented on cclient/request/get_transactions_to_approve.c
> +    get_transactions_to_approve_req_t* const req, uint32_t const depth) {
Need indention here.

2018-12-17 11:48 UTC, jserv commented on cclient/request/get_transactions_to_approve.c
> +  memcpy(req->reference, reference, FLEX_TRIT_SIZE_243);
Ditto. Indention.

2018-12-17 11:57 UTC, thibault-martinez commented on cclient/request/get_transactions_to_approve.c
> +    get_transactions_to_approve_req_t* const req, uint32_t const depth) {
Not following our coding style.

2018-12-17 11:57 UTC, thibault-martinez commented on cclient/request/get_transactions_to_approve.c
> +  memcpy(req->reference, reference, FLEX_TRIT_SIZE_243);
Ditto.

2018-12-18 09:50 UTC, th0br0 approved these changes

2018-12-18 09:50 UTC, th0br0 commented on cclient/request/get_transactions_to_approve.c
>        (get_transactions_to_approve_req_t*)malloc(
This leaves depth uninitialised. Could we calloc here?

2018-12-18 09:50 UTC, th0br0 commented on cclient/request/get_transactions_to_approve.c
> +    req->reference = NULL;
With calloc ^ not necessary

2018-12-18 10:10 UTC, merged