Ledger validator - use traversal utils
iotaledger/entangled pull request #454
Opened 2018-10-30 13:26 UTC by tsvisabo

- Refactor `tangle_traversal_dfs_to_genesis` - enable storing `analyzed_hashes` + remove unused param
- `get_latest_delta` - remove `counted_hashes` - (`bundle`  arg was accumulating transactions from every scanned bundle and i guess that's the reason for the additional counted_hashes set)
- Use traversal in `get_latest_delta`

2018-10-30 13:34 UTC, th0br0 commented on common/model/bundle.c
> +  if (bundle && *bundle){
:+1:

2018-10-30 14:03 UTC, th0br0 requested changes

2018-10-30 14:03 UTC, th0br0 commented on consensus/transaction_solidifier/transaction_solidifier.h
> +    transaction_solidifier_t *const ts, iota_consensus_defs_t *const defs,
Could you add comments to the methods here detailing what they do? 
at least the check_solidity & such, init/start/stop/destroy arguably don't need that

2018-10-30 14:03 UTC, th0br0 commented on consensus/utils/tangle_traversals.c
> +      analyzed_hashe_param ? analyzed_hashe_param : &analyzed_hashes_local;
typo `hashe_param`

2018-10-30 14:05 UTC, tsvisabo commented on consensus/transaction_solidifier/transaction_solidifier.h
> +    transaction_solidifier_t *const ts, iota_consensus_defs_t *const defs,
That will be helpful, it should be done in a different PR IMO, though i was thinking that next PR will even eliminate that function as we discussed

2018-10-31 09:08 UTC, th0br0 approved these changes

2018-10-31 09:09 UTC, thibault-martinez requested changes

2018-10-31 09:09 UTC, thibault-martinez commented on consensus/ledger_validator/ledger_validator.c
> +  struct _trit_array curr_hash = {NULL, NUM_TRITS_HASH, FLEX_TRIT_SIZE_243, 0};
Can you add member designators here ?

2018-10-31 09:27 UTC, thibault-martinez approved these changes

2018-10-31 10:47 UTC, merged