main: print tx stats log
iotaledger/entangled pull request #472
Opened 2018-11-05 11:08 UTC by thibault-martinez

The main is now printing tx stats logs.

Sample: `2018-11-05 12:04:21:           main:   INFO: Transactions: to process 0, to broadcast 0, to request 49, count 3956`

Depends on #470 

Should make #260 easier to implement.

# Test Plan:
Not applicable.

2018-11-05 11:17 UTC, th0br0 requested changes

2018-11-05 11:17 UTC, th0br0 commented on ciri/main.c
> +  while (true) {
This breaks shutdown because it won't ever be interrupted?

2018-11-05 11:23 UTC, thibault-martinez commented on ciri/main.c
> +  while (true) {
It temporarily replaces a `sleep` with an arbitrary value so until #260 is merged we won't really have a sane shutdown.

2018-11-05 11:24 UTC, thibault-martinez commented on ciri/main.c
> +  while (true) {
We can wait until #260 is merged to merge this one.

2018-12-10 07:49 UTC, th0br0 approved these changes

2018-12-10 08:13 UTC, merged