trinary: fix slice test segmentation fault
iotaledger/entangled pull request #476
Opened 2018-11-05 16:03 UTC by thibault-martinez

# Test Plan:
Trinary tests must pass

2018-11-05 16:11 UTC, th0br0 approved these changes

2018-11-05 16:16 UTC, thibault-martinez commented
Seems like with this I avoided the cause, but not solved it. Still investigating.

2018-11-05 16:21 UTC, th0br0 requested changes
Doesn't this also potentially lead to bad data?

2018-11-05 17:03 UTC, thibault-martinez commented
The root cause has been identified after a very productive call with @ifullgaz :)

2018-11-06 08:11 UTC, th0br0 approved these changes

2018-11-06 08:31 UTC, merged