cclient: fixing the threshold misunderstanding.
iotaledger/entangled pull request #506
Opened 2018-11-12 15:57 UTC by oopsmonk

the meaning of threshold is different in get_inputs and get_balances.
refer to [createGetInputs.ts](https://github.com/iotaledger/iota.js/blob/next/packages/core/src/createGetInputs.ts) and [createGetBalances.ts](https://github.com/iotaledger/iota.js/blob/next/packages/core/src/createGetBalances.ts)

# Test Plan:
CI must pass

2018-11-12 16:15 UTC, th0br0 requested changes

2018-11-12 16:15 UTC, th0br0 commented on cclient/iota_client_extended_api.c
> +  blances_req->threshold = 100;  // currently `100` should be used
could you also address the `blances` typo?

2018-11-12 16:15 UTC, th0br0 commented on cclient/response/get_balances.c
> +  size_t balance = 0;
should use & return `uint64_t`

2018-11-12 16:15 UTC, th0br0 commented on cclient/response/get_balances.c
> +    balance = strtol(*p, &endptr, 10);
we move the string->int conversion to the JSON layer

2018-11-13 02:47 UTC, oopsmonk commented
@th0br0 thanks for your advice, typo and conversion are fixed.

2018-11-13 03:54 UTC, wusyong commented on cclient/iota_client_extended_api.c
> +      get_balances_res_total_balance(balances_res, threshold);
According to [filterByThreshold](https://github.com/iotaledger/iota.js/blob/next/packages/core/src/createGetInputs.ts#L147), `threshold` in `get_inputs` should mean "total balance >= threshold" instead of "each balance > threshold". And input addresses should also be filtered I think.

2018-11-13 04:29 UTC, oopsmonk commented on cclient/iota_client_extended_api.c
> +      get_balances_res_total_balance(balances_res, threshold);
yes, you are right, thanks.

2018-11-14 07:38 UTC, th0br0 approved these changes

2018-11-14 07:39 UTC, merged