mam/v2: sponge - decision is to stay with trit_t
iotaledger/entangled pull request #527
Opened 2018-11-14 15:56 UTC by tsvisabo

- Revert to trits as it was decided we keep that type and for performance it is best that sponge transform 
  function will operate on "plain" trits

2018-11-14 16:16 UTC, thibault-martinez requested changes

2018-11-14 16:16 UTC, thibault-martinez commented on mam/v2/curl.c
> +    trits_copy(x = state, stack);
Can you put this assignment outside ?

2018-11-14 16:16 UTC, thibault-martinez commented on mam/v2/curl.c
> +  trit_t t, prev_t = trits_get1(state);
Could you rename `prev_t` to simply `prev` to avoid type confusion ?

2018-11-14 16:16 UTC, thibault-martinez commented on mam/v2/prng.c
> +static void flex_from_trits(trits_t t, flex_trit_t *flex_trits) {
Put this one in common ?

2018-11-14 16:16 UTC, thibault-martinez commented on mam/v2/tests/common.h
> +#include "../trits.h"
Avoid relative paths

2018-11-14 16:16 UTC, thibault-martinez commented on mam/v2/trits.h
> +#include "../../common/trinary/trit_tryte.h"
Relative path

2018-11-14 16:29 UTC, tsvisabo commented on mam/v2/trits.h
> +#include "../../common/trinary/trit_tryte.h"
CLion...

2018-11-14 16:57 UTC, tsvisabo commented on mam/v2/prng.c
> +static void flex_from_trits(trits_t t, flex_trit_t *flex_trits) {
for now it will be in trits.h

2018-11-15 07:40 UTC, thibault-martinez approved these changes

2018-11-15 07:41 UTC, merged