conf: add a coordinator CLI option
iotaledger/entangled pull request #559
Opened 2018-11-23 10:57 UTC by thibault-martinez

Fixes #461 

# Test Plan:
CI must pass

2018-11-26 17:41 UTC, th0br0 requested changes
What's this needed for? We're reading the coordinator from the snapshot json file, no?

2018-11-26 17:56 UTC, thibault-martinez commented
We do, but with the snapshot json file we are limited to either the mainnet coo or the testnet coo but not a custom one. This is the equivalent of IRI's `--testnet-coordinator`

2018-11-26 20:36 UTC, th0br0 commented
Right, but people could just as well provide an alternative snapshot.json file? 
That'd be better IMHO because they might also want to change the starting index as part of passing in a separate coordinator address?

2018-11-27 17:52 UTC, th0br0 approved these changes

2018-11-27 18:15 UTC, merged