gossip: transaction requester thread
iotaledger/entangled pull request #593
Opened 2018-12-05 13:15 UTC by thibault-martinez

Fixes #590 

# Test Plan:
CI

2018-12-05 13:24 UTC, th0br0 requested changes

2018-12-05 13:24 UTC, th0br0 commented on gossip/components/transaction_requester.c
> +    if (requester_size(transaction_requester) > REQUESTER_THRESHOLD) {
let's use a label here and invert the condition?

2018-12-05 13:24 UTC, th0br0 commented on gossip/components/transaction_requester.c
> +          if (neighbor_send(transaction_requester->node, &iter->data,
is this thread safe?

2018-12-06 08:14 UTC, thibault-martinez commented on gossip/components/transaction_requester.c
> +          if (neighbor_send(transaction_requester->node, &iter->data,
Not 100% thread-safe, I planned on refactoring the whole neighbour layer when doing `getNeighbors`, `addNeighbors` and `removeNeighbors` API calls (maybe next)

2018-12-07 12:47 UTC, thibault-martinez commented on gossip/components/transaction_requester.c
> +          if (neighbor_send(transaction_requester->node, &iter->data,
Fixed in #599

2018-12-10 10:24 UTC, th0br0 approved these changes

2018-12-10 14:25 UTC, th0br0 approved these changes

2018-12-10 16:28 UTC, merged