Model seperation 2
iotaledger/entangled pull request #598
Opened 2018-12-05 22:50 UTC by tsvisabo

#589 replaces

2018-12-07 10:47 UTC, thibault-martinez requested changes

2018-12-07 10:47 UTC, thibault-martinez commented on common/storage/sql/schema.sql
> +  snapshot_index INTEGER NOT NULL DEFAULT 0,
Can you reflect that on `ciri-mainnet.db` and `ciri-testnet.db` ?

2018-12-07 10:47 UTC, thibault-martinez commented on consensus/milestone_tracker/milestone_tracker.c
> +              MODEL_TRANSACTION_META_ALL) == RC_OK &&
Note to myself: we actually only need the obsolete tag from this transaction so we might want to load only this field

2018-12-10 17:52 UTC, tsvisabo commented
as we are taking a new model separation, this PR is not relevant

2018-12-10 17:52 UTC, closed without merging