cclient: fix threshold comparison in get_inputs
iotaledger/entangled pull request #615
Opened 2018-12-13 05:59 UTC by wusyong

* Fix threshold comparison in get_inputs to be same as iota.js [1]
* Add final check for insufficient balance

[1] https://github.com/iotaledger/iota.js/blob/next/packages/core/src/createGetInputs.ts#L147

# Test Plan:
CI must pass

2018-12-13 06:06 UTC, jserv commented on cclient/iota_client_extended_api.c
>          out_input->total_balance += tmp_balance;
How about moving `tmp_balance` to this scope?

2018-12-17 11:19 UTC, jserv commented
Rebasing is required.

2018-12-18 08:35 UTC, oopsmonk requested changes

2018-12-18 08:35 UTC, oopsmonk commented on cclient/iota_client_extended_api.c
> +      ret_code = RC_CCLIENT_INSUFFICIENT_BALANCE;
please add `log_warning` here.

2018-12-18 14:53 UTC, oopsmonk approved these changes

2018-12-18 15:00 UTC, thibault-martinez commented on cclient/iota_client_extended_api.c
> +        tmp_balance = get_balances_res_balances_at(balances_res, counter);
What is the tmp for ? Can't you just directly add to `out_input->total_balance` ?

2018-12-19 06:34 UTC, thibault-martinez approved these changes
@wusyong Thanks for the PR !

2018-12-19 06:51 UTC, merged