gossip/processor: use PTrit hashing for improved performance
iotaledger/entangled pull request #620
Opened 2018-12-14 19:29 UTC by th0br0

2018-12-14 20:01 UTC, thibault-martinez commented on gossip/components/processor.c
> +    memset(&flex_hash, FLEX_TRIT_NULL_VALUE, sizeof(flex_hash));
```suggestion
    memset(flex_hash, FLEX_TRIT_NULL_VALUE, sizeof(flex_hash));
```

2018-12-14 20:01 UTC, thibault-martinez commented on gossip/components/processor.c
> +      bytes_to_trits(&packets[j].content, PACKET_SIZE, tx, NUM_TRITS_SERIALIZED_TRANSACTION);
```suggestion
      bytes_to_trits(packets[j].content, PACKET_SIZE, tx, NUM_TRITS_SERIALIZED_TRANSACTION);
```

2018-12-14 20:01 UTC, thibault-martinez commented on gossip/components/processor.c
> +      flex_trits_from_trits(&flex_hash, HASH_LENGTH_TRIT, hash, HASH_LENGTH_TRIT, HASH_LENGTH_TRIT);
```suggestion
      flex_trits_from_trits(flex_hash, HASH_LENGTH_TRIT, hash, HASH_LENGTH_TRIT, HASH_LENGTH_TRIT);
```

2018-12-14 20:01 UTC, thibault-martinez commented on gossip/components/processor.c
> +      if (process_packet(processor, &packets[j], &flex_hash) != RC_OK) {
```suggestion
      if (process_packet(processor, &packets[j], flex_hash) != RC_OK) {
```

2018-12-19 03:14 UTC, jserv commented on common/curl-p/ptrit.c
> +      length / HASH_LENGTH_TRIT + ((length % HASH_LENGTH_TRIT) ? 1 : 0);
How about change from `(length % HASH_LENGTH_TRIT) ? 1 : 0` to `!!(length % HASH_LENGTH_TRIT)`?

2018-12-20 13:25 UTC, thibault-martinez requested changes

2018-12-20 13:25 UTC, thibault-martinez commented on common/model/transaction.c
> +                                     bool computeHash) {
snake_case

2018-12-20 13:25 UTC, thibault-martinez commented on consensus/test_utils/tangle.c
> +                              bool computeHash) {
snake_case

2018-12-20 13:25 UTC, thibault-martinez commented on consensus/test_utils/tangle.h
> +                              bool computeHash);
snake_case

2018-12-20 13:25 UTC, thibault-martinez commented on common/curl-p/ptrit.c
> +      ptrit_sbox(ctx->state, &s.state);
`&s.state` will produce a warning and I'm not sure it'll work properly on all archs

2018-12-20 13:25 UTC, thibault-martinez commented on common/curl-p/ptrit.c
> +      ptrit_sbox(&s.state, ctx->state);
Ditto

2018-12-20 13:25 UTC, thibault-martinez commented on common/model/transaction.h
> +                                           bool computeHash);
snake_case

2018-12-20 13:25 UTC, thibault-martinez commented on gossip/components/processor.c
> +  memcpy(transaction_hash(&transaction), curl_hash, FLEX_TRIT_SIZE_243);
Use `transaction_set_hash` instead

2018-12-20 14:25 UTC, thibault-martinez approved these changes

2018-12-20 16:29 UTC, merged