Generic type map
iotaledger/entangled pull request #639
Opened 2018-12-23 16:02 UTC by tsvisabo

- Implement generic type map (fixed hash size, do we want to support different sizes?)

2018-12-23 16:12 UTC, thibault-martinez reviewed
Do we still need the previous `hash_int_map_t` then ?

2018-12-23 17:15 UTC, thibault-martinez requested changes

2018-12-23 17:15 UTC, thibault-martinez commented on common/storage/sql/sqlite3/tests/test_sqlite3.c
> +    TEST_ASSERT(hash_to_int64_t_map_add(&state_delta1, hash, i) == RC_OK);
Why can't you use `state_delta_add` here ?

2018-12-23 17:15 UTC, thibault-martinez commented on consensus/snapshot/state_delta.c
> +    if ((ret = hash_to_int64_t_map_add(state, hash, value)) != RC_OK) {
Why can't you use state_delta_add here ?

2018-12-23 17:15 UTC, thibault-martinez commented on consensus/snapshot/state_delta.c
> +    if ((ret = hash_to_int64_t_map_add(
`state_delta_add` ?

2018-12-24 02:37 UTC, thibault-martinez requested changes

2018-12-24 02:37 UTC, thibault-martinez commented on consensus/exit_probability_randomizer/tests/test_exit_probability_randomizer.c
> +  // TEST_ASSERT_EQUAL_INT64(out.cw_ratings->value, num_approvers + 1);
Can we uncomment ?

2018-12-24 06:36 UTC, tsvisabo commented on consensus/exit_probability_randomizer/tests/test_exit_probability_randomizer.c
> +  // TEST_ASSERT_EQUAL_INT64(out.cw_ratings->value, num_approvers + 1);
Thanks

2018-12-24 13:52 UTC, thibault-martinez approved these changes

2018-12-24 13:52 UTC, merged