storage: TLS prepared statements
iotaledger/entangled pull request #656
Opened 2019-01-04 21:28 UTC by thibault-martinez

- Extracts common sqlite3 wrappers in their own compilation unit
- Adds TLS prepared statements

# Test Plan:
CI

2019-01-04 22:05 UTC, th0br0 requested changes

2019-01-04 22:05 UTC, th0br0 commented on common/storage/connection.h
> +  void* data;
Can't we make connection opaque?

2019-01-04 22:19 UTC, thibault-martinez commented on common/storage/connection.h
> +  void* data;
Will do

2019-01-05 22:22 UTC, th0br0 approved these changes

2019-01-05 22:22 UTC, th0br0 commented on common/storage/sql/sqlite3/connection.c
> +    log_error(SQLITE3_LOGGER_ID, "Preparing statements failed\n");
Let's also log the actual error here via `RC_RESOLVE_FORMAT_STR`

2019-01-05 22:22 UTC, th0br0 commented on common/storage/sql/sqlite3/connection.c
> +    log_error(SQLITE3_LOGGER_ID, "Finalizing statements failed\n");
Let's also log the actual error here via `RC_RESOLVE_FORMAT_STR`

2019-01-05 22:22 UTC, th0br0 commented on common/storage/connection.h
> +} opaque_connection_t;
let's call this `storage_connection_t`?

2019-01-06 00:53 UTC, merged