utils/logger: lock depending on the log level
iotaledger/entangled pull request #672
Opened 2019-01-10 01:24 UTC by thibault-martinez

At the cost of a redundant check (the log level is already checked by `logger_va`), this PR locks only when the log level actually allows to log.
Starting from log level `INFO`, there is almost no lock anymore.

# Test Plan:
CI

2019-01-10 01:27 UTC, th0br0 approved these changes

2019-01-10 01:29 UTC, th0br0 commented on utils/logger_helper.c
> +  id = logger_id_request(logger_id);
You're requesting outside the lock now. Is that safe?

2019-01-10 01:41 UTC, thibault-martinez commented on utils/logger_helper.c
> +  id = logger_id_request(logger_id);
The lock is mainly here to synchronize stdout.
`logger_id_request` returns the id if it was already created and we never log before having created the logger so it should be ok.

2019-01-10 07:01 UTC, th0br0 requested changes
Thibault Martinez [7:09 AM]
Let's not merge #672 yet, you made me doubt I need to think

2019-01-11 10:32 UTC, th0br0 approved these changes

2019-01-11 10:33 UTC, th0br0 approved these changes

2019-01-11 10:33 UTC, merged