Checksum support
iotaledger/entangled pull request #7
Opened 2018-06-18 06:54 UTC by tsvisabo

2018-06-18 13:50 UTC, th0br0 requested changes

2018-06-18 13:50 UTC, th0br0 commented on common/helpers/tests/test_checksum.cpp
> +
could you fix the newlines here?

2018-06-18 13:50 UTC, th0br0 commented on common/kerl/hash.c
> +char digest[HASH_LENGTH];
formatting

2018-06-20 08:07 UTC, th0br0 requested changes

2018-06-20 08:07 UTC, th0br0 commented on common/helpers/checksum.c
> +#define RADIX 3
don't we have this `#define`d elsewhere already?

2018-06-20 08:07 UTC, th0br0 commented on common/helpers/checksum.c
> +  char hash[HASH_LENGTH / RADIX];
not needed

2018-06-20 08:07 UTC, th0br0 commented on common/helpers/checksum.c
> +  trits_to_trytes((trit_t*)trits_hash, (tryte_t*)hash, HASH_LENGTH);
move this after `checksumTrytes` is alloced so you can just write the trytes to there

2018-06-20 08:07 UTC, th0br0 commented on common/helpers/checksum.c
> +  memcpy(checksumTrytes, &hash[HASH_LENGTH / RADIX - checksumLength],
not needed with ^

2018-06-20 08:07 UTC, th0br0 commented on common/helpers/checksum.c
> +  checksumTrytes[checksumLength] = '\0';
`calloc` already initialises to 0

2018-06-24 07:06 UTC, tsvisabo commented on common/helpers/checksum.c
> +#define RADIX 3
move to trit_tryte.h

2018-06-24 07:06 UTC, tsvisabo commented on common/helpers/checksum.c
> +  char hash[HASH_LENGTH / RADIX];
removed

2018-06-25 11:22 UTC, th0br0 approved these changes

2018-06-25 11:24 UTC, merged