mam/v2/mss - renaming and cleaning
iotaledger/entangled pull request #709
Opened 2019-01-23 14:56 UTC by tsvisabo

2019-01-23 15:00 UTC, jserv commented on mam/v2/mss/mss.c
> +    trits_t hashed_hashes /*!< [out] hash value of their parent */
The name sounds weird. `hashed_hashes`?

2019-01-24 06:45 UTC, tsvisabo commented on mam/v2/mss/mss.c
> +    trits_t hashed_hashes /*!< [out] hash value of their parent */
yes, i agree, but that's what it is actually, we hash to hashes to get their hash result :)
(Merkle tree)

2019-01-24 08:14 UTC, thibault-martinez requested changes

2019-01-24 08:14 UTC, thibault-martinez commented on mam/v2/ntru/poly.c
> +  poly_dcoeff_t height;
This shouldn't be `height`

2019-01-24 08:14 UTC, thibault-martinez commented on mam/v2/ntru/poly.c
> +  poly_dcoeff_t height = c;
Ditto

2019-01-24 08:14 UTC, thibault-martinez commented on mam/v2/pb3/pb3.c
> +  /* one extra tryte to encode `height` */
Ditto

2019-01-24 08:14 UTC, thibault-martinez commented on mam/v2/test_utils/test_utils.c
> +    mss_init(m, r, spongos, w, height, n1, n2);
Ditto

2019-01-24 11:02 UTC, thibault-martinez requested changes

2019-01-24 11:02 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +    dbg_printf("========================\nD = %height\n", curr_height);
Some more frenzy replacing :trollface:

2019-01-24 11:02 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +      dbg_printf("------------------------\nskn = %height\n", mss->skn);
Ditto

2019-01-24 11:02 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +    dbg_printf("  nodes = %height\n", m->hash_node_count);
Ditto

2019-01-24 11:52 UTC, thibault-martinez requested changes

2019-01-24 11:52 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +      dbg_printf("------------------------\nskn = %mss->skn\n", mss->skn);
Last one ?

2019-01-24 12:20 UTC, thibault-martinez approved these changes

2019-01-24 12:32 UTC, merged