Added toolchain project for cross compiling.
iotaledger/entangled pull request #76
Opened 2018-07-23 09:17 UTC by oopsmonk

Fixing #16 
Added default cross toolchains include aarch64(armv8), armv7, x86_64, i686, and a python script to generate bazel toolchain files (CROSSTOOL, BUILDs).

Aarch64 Testing:
`bazel build --crosstool_top=@iota_toolchains//tools/aarch64--glibc--stable-2018.02-2:toolchain --cpu=aarch64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --verbose_failures //cclient:api`

2018-07-23 13:07 UTC, jserv commented
By the way, can you provide instructions to re-generate toolchain from scratch? Something like [crosstool-NG](https://crosstool-ng.github.io/) might work out of box.

2018-07-24 06:33 UTC, th0br0 commented
@jserv that is available here https://github.com/bootlin/toolchains-builder

2018-07-24 06:33 UTC, th0br0 requested changes

2018-07-24 06:33 UTC, th0br0 commented on WORKSPACE
> +    name = "iota_toolchains",
remove

2018-07-24 06:40 UTC, th0br0 commented
```
/root/.cache/bazel/_bazel_root/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bootlin_i686_toolchain/bin/../lib/gcc/i686-buildroot-linux-gnu/8.1.0/../../../../i686-buildroot-linux-gnu/bin/ld: bazel-out/i686-opt/bin/common/trinary/libtryte_long.a(tryte_long.o): in function `long_to_trytes':
--
  | /proc/self/cwd/common/trinary/tryte_long.c:57: undefined reference to `pow'
```

You're missing parameters like the below from your `CROSSTOOL` files:
```
  cxx_flag: "-std=c++11"
  linker_flag: "-lpthread"
  linker_flag: "-L/usr/local/llvm_scratch/libcxx_msan/lib"
  linker_flag: "-lc++"
  linker_flag: "-lc++abi"
  linker_flag: "-Wl,-rpath,/usr/local/llvm_scratch/libcxx_msan/lib"
  linker_flag: "-lm"
  linker_flag: "-fuse-ld=gold"
  linker_flag: "-B/usr/bin"
  linker_flag: "-B/usr/bin"
  linker_flag: "-Wl,--build-id=md5"
  linker_flag: "-Wl,--hash-style=gnu"
  cxx_builtin_include_directory: "/usr/local/llvm_scratch/libcxx_msan/include/c++/v1"
  cxx_builtin_include_directory: "/usr/local/llvm_scratch/libcxx_msan/include/"
  cxx_builtin_include_directory: "/usr/include/clang/4.0.0/include"
  cxx_builtin_include_directory: "/usr/lib/clang/4.0.0/include"
  cxx_builtin_include_directory: "/usr/lib/llvm-4.0/lib/clang/4.0.0/include"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include/x86_64-linux-gnu"
  cxx_builtin_include_directory: "/usr/include"
```

2018-07-24 17:26 UTC, oopsmonk commented
The test function has an error in gcc 8.1, but with no problem in gcc 7.3. 
GCC-8  checks the comparison function with static assertions. 
See https://gcc.gnu.org/gcc-8/porting_to.html#comparison-object
```
cppclient/tests/api_json.cc:50:3:   required from here
bazel-out/i686-opt/bin/external/nlohmann/_virtual_includes/json/nlohmann/detail/conversions/to_json.hpp:312:45: error: static assertion failed: could not find to_json() method in T's namespace
         static_assert(sizeof(BasicJsonType) == 0,
~~~~~~~~~~~~~~~~~~~~~~^~~~
```

2018-07-25 08:09 UTC, th0br0 approved these changes

2018-07-25 08:10 UTC, merged