Optimized curl transform formulas
iotaledger/entangled pull request #803
Opened 2019-02-09 14:13 UTC by muXxer

powsrv.io Team optimized the curl transform formulas.

On my machine it's around 7% faster than before.

# Test Plan:
To benchmark the results I changed the test_curlp_ptrit.c locally on my machine:
```
int main(void) {
  UNITY_BEGIN();

  RUN_TEST(test_curl_p_27_works);
  for(size_t i = 0; i < 50000; i++)
  {
    RUN_TEST(test_curl_p_81_works);
  } 

  return UNITY_END();
}
```

2019-02-11 10:02 UTC, thibault-martinez commented
Some benchmarks done in https://github.com/iotaledger/iri/pull/1330

2019-02-16 17:07 UTC, Wollac reviewed
The changes reduce the number of bitwise operations, while still being correct under the assumption that `.low` and `.high` never *both* have a 0-bit at the same index, which is exactly a characteristic of the `ptrit` encoding.
This assumption is correct, if e.g. `trits_to_ptrits` is used for the conversion and it is a loop invariant in `ptrit_sbox`, but it is never explicitly validated before entering this function.

I proposed a few changes to the order, to make it clearer which parts of the computation have actually been changed.
These changes can be validated more formally for every bit:

<img width="500" alt="review" src="https://user-images.githubusercontent.com/4930426/52902429-e71fd780-3210-11e9-86cc-3cd8117c29d5.png">

2019-02-16 17:07 UTC, Wollac commented on common/curl-p/ptrit.c
> +    c[i].high = delta | (alpha ^ s[CURL_INDEX[i + 1]].high);
```suggestion
    c[i].high = (alpha ^ s[CURL_INDEX[i + 1]].high) | delta;
```
The formula for `c[i].high` remains unchanged.

2019-02-16 17:07 UTC, Wollac commented on common/curl-p/ptrit.c
> +    delta = beta ^ s[CURL_INDEX[i + 1]].low;
```suggestion
    delta = alpha & (s[CURL_INDEX[i + 1]].low ^ beta);
```

2019-02-16 17:07 UTC, Wollac commented on common/curl-p/ptrit.c
> +    c[i].low = ~(delta & alpha);
```suggestion
    c[i].low = ~delta;
```

2019-02-17 08:20 UTC, tsvisabo requested changes

2019-02-17 08:20 UTC, tsvisabo commented on common/curl-p/ptrit.c
> +    c[i].high = delta | (alpha ^ s[CURL_INDEX[i + 1]].high);
Hi @muXxer , thanks for this PR, can you check if the performance gain is still the same after @Wollac  order changes suggestions and integrate them to your PR?

2019-03-06 20:46 UTC, muXxer commented
Performance gain is the same with wollacs changes.
Last question, should we rename the "delta" now to "gamma"? @Wollac 
Now we only have "alpha, beta, delta". Maybe this is confusing :)

2019-03-07 07:28 UTC, tsvisabo submitted a review, later dismissed

2019-03-07 07:29 UTC, tsvisabo commented
@muXxer can you rebase and i'll re-approve?

2019-03-07 07:59 UTC, muXxer commented
@tsvisabo done :)

2019-03-07 08:09 UTC, tsvisabo approved these changes

2019-03-07 08:18 UTC, merged