Mam2 troika
iotaledger/entangled pull request #850
Opened 2019-02-26 13:30 UTC by tsvisabo

- Integrate Troika from https://github.com/Troikahash/reference
- Use Troika for transformation

2019-02-26 13:40 UTC, thibault-martinez requested changes

2019-02-26 13:40 UTC, thibault-martinez commented on common/troika/troika.c
> + *
Remove space

2019-02-26 13:40 UTC, thibault-martinez commented on common/troika/troika.c
> +Permission is hereby granted, free of charge, to any person obtaining a copy
Can you add `* ` on every line like all out copyrights ?

2019-02-26 13:40 UTC, thibault-martinez commented on common/troika/troika.h
> + *
Same here

2019-02-26 13:40 UTC, thibault-martinez commented on common/troika/troika.h
> +Permission is hereby granted, free of charge, to any person obtaining a copy
Same here

2019-02-26 13:40 UTC, thibault-martinez commented on mam/v2/sponge/sponge.c
>  // TODO mam2: replace sponge transformation function #773
Remove  comment

2019-02-26 13:40 UTC, thibault-martinez commented on mam/v2/troika/troika.c
> +/*void troika_permutation(trit_t *state, unsigned long num_rounds)*/
Remove ?

2019-02-26 13:40 UTC, thibault-martinez commented on mam/v2/troika/troika.h
> +/*#define MAM2_TROIKA_NUM_ROUNDS 12*/
Remove ?

2019-02-26 15:04 UTC, thibault-martinez requested changes

2019-02-26 15:04 UTC, thibault-martinez commented on common/troika/troika.h
> + *
Hasn't been removed :(

2019-02-26 15:04 UTC, thibault-martinez commented on common/troika/troika.h
> +Permission is hereby granted, free of charge, to any person obtaining a copy
Hasn't been added :(

2019-02-26 15:04 UTC, thibault-martinez commented on mam/v2/troika/troika.h
> +/*#define MAM2_TROIKA_NUM_ROUNDS 12*/
Not removed :(

2019-02-26 15:10 UTC, thibault-martinez submitted a review, later dismissed

2019-02-26 20:31 UTC, thibault-martinez requested changes

2019-02-26 20:31 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +#include "utils/handles/rand.h"
Why ?

2019-02-26 20:31 UTC, thibault-martinez commented on mam/v2/mss/tests/BUILD
> +        "//utils/handles:rand",
Why ?

2019-02-27 06:43 UTC, tsvisabo commented on mam/v2/mss/tests/test_mss.c
> +#include "utils/handles/rand.h"
Fixed with usage

2019-02-27 06:43 UTC, tsvisabo commented on mam/v2/mss/tests/BUILD
> +        "//utils/handles:rand",
Fixed with usage

2019-02-27 08:17 UTC, thibault-martinez requested changes

2019-02-27 08:17 UTC, thibault-martinez commented on mam/v2/mss/tests/test_mss.c
> +      if (curr_height > 1 && ((rand() % 2) == 0)) {
Use `rand_handle_rand`

2019-02-27 08:22 UTC, thibault-martinez approved these changes

2019-02-27 09:02 UTC, merged

2019-02-27 11:18 UTC, Citrullin commented
@thibault-martinez @tsvisabo Is it clear that the reference implementation is not supposed to be used in production like environments? There are some problems with the reference implementation. E.g. [this one.](https://github.com/Troikahash/reference/issues/2)
The performance of the reference implementation is also not really nice. One IOTA community dev already improved the implementation a lot. You can find the repo [here](https://github.com/c-mnd/troika). It is ~10 times faster than the reference implementation, and he did fix the squeeze absorb bug.

2019-02-27 13:17 UTC, shufps commented
for fixed absorb this [here](https://github.com/c-mnd/troika/pull/1). It hasn't been merged in the optimized troika version yet ... I'm not sure if it will happen since the creator of the optimizations is anonymous and he only created the github repo for this one project.