mobile/android: Zero out seed even if function returns early
iotaledger/entangled pull request #860
Opened 2019-02-28 01:27 UTC by rajivshah3

Calls `memset_safe` even if the function returns early because of an error. I forgot to add this to my earlier PR for `memset` in Android

# Test Plan:
- Testing locally on Android emulator

2019-02-28 01:32 UTC, th0br0 requested changes
General reordering & a label would be much cleaner, but this works for now I guess.

2019-02-28 01:32 UTC, th0br0 commented on mobile/android/Interface.cpp
> +    memset_safe((void*)seed, 81, 0, 81);
these are trits

2019-02-28 01:33 UTC, rajivshah3 commented
That was fast 😄

2019-02-28 01:33 UTC, rajivshah3 commented on mobile/android/Interface.cpp
> +    memset_safe((void*)seed, 81, 0, 81);
Yikes 🤦‍♂️

2019-03-05 04:25 UTC, rajivshah3 commented
@thibault-martinez if you have a chance, could you review?

2019-03-22 03:51 UTC, oopsmonk requested changes

2019-03-22 03:51 UTC, oopsmonk commented on mobile/android/Interface.cpp
> +    memset_safe((void*)seed, 81, 0, 81);
you should call `ReleaseStringUTFChars` when `seed` is not used any more otherwise, it would result in a memory leak.

2019-03-22 04:16 UTC, oopsmonk commented
Just noticed that `interface.cpp` has memory leak problems, the get method should be paired with release in JNI spec. say `GetByteArrayElements`/`ReleaseByteArrayElements`, `GetStringUTFChars`/`ReleaseStringUTFChars`.

2019-04-08 07:13 UTC, oopsmonk requested changes

2019-04-08 07:13 UTC, oopsmonk commented on mobile/android/Interface.cpp
> +  const char* ctrunk = env->GetStringUTFChars(trunk, 0);
const placement. const char* -> char const* for consistency

2019-04-08 07:13 UTC, oopsmonk commented on mobile/android/Interface.cpp
>      const char* txTrytes = env->GetStringUTFChars(txString, 0);
ditto

2019-04-09 02:30 UTC, oopsmonk approved these changes

2019-04-09 02:47 UTC, merged

2019-04-09 02:50 UTC, oopsmonk commented
thanks :)