log to review BUNDLE_INVALID_SIGNATURE bundle status
iotaledger/entangled pull request #942
Opened 2019-03-09 05:07 UTC by ed2k

code to review invalid bundle status

2019-03-10 08:55 UTC, tsvisabo approved these changes
Thanks @ed2k

2019-03-10 08:57 UTC, th0br0 commented
This should probably be a debug log, else a log flood can be triggered
maliciously?

On Sun, 10 Mar 2019, 16:55 Tsvi Sabo, <notifications@github.com> wrote:

> *@tsvisabo* approved this pull request.
>
> Thanks @ed2k <https://github.com/ed2k>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/iotaledger/entangled/pull/942#pullrequestreview-212593028>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAB5FLxrfHJSA5T1K5F2vbZ57lmxU8mIks5vVMh1gaJpZM4bmfPQ>
> .
>

2019-03-10 09:06 UTC, tsvisabo requested changes
See @th0br0 's comment, please use `log_debug`

2019-03-13 07:32 UTC, tsvisabo approved these changes

2019-03-15 03:42 UTC, merged