CClient - TLS socket and https client.
iotaledger/entangled pull request #944
Opened 2019-03-11 08:19 UTC by oopsmonk

This PR implemented tls socket and https client, fixed #724 
Removed `utils/containers/lock_free`

# Test Plan:
CI pass

2019-03-11 08:42 UTC, thibault-martinez requested changes

2019-03-11 08:42 UTC, thibault-martinez commented on cclient/http/http.h
> +// socket buffer can overwrite thought config
through ?

2019-03-11 08:42 UTC, thibault-martinez commented on utils/handles/socket.c
> +  sprintf(port_string, "%d", port);
As `port_string` is not guaranteed to be 0-initialized, shouldn't we do something like `sprintf(port_string, "%06d", port);` ?

2019-03-11 08:42 UTC, thibault-martinez commented on cclient/http/http.c
> +    if ((result = send_headers_to_iota_service(sockfd, http_settings,
Can we uniform names between http and https ?
- `connect_to_iota_service ` and `tls_socket_connect `
- `close_socket `  and  `tls_socket_close `
- `send_headers_to_iota_service ` and `https_request_header `
- `send_data_to_iota_service ` and `https_request_data `
- `read_data_from_iota_service `and `https_response_read `

2019-03-11 09:00 UTC, oopsmonk commented on cclient/http/http.h
> +// socket buffer can overwrite thought config
a gcc preprocessor macro

2019-03-11 09:05 UTC, thibault-martinez commented on cclient/http/http.h
> +// socket buffer can overwrite thought config
I meant, `thought` is a typo ?

2019-03-11 09:22 UTC, oopsmonk commented on cclient/http/http.h
> +// socket buffer can overwrite thought config
haha..typo

2019-03-12 11:30 UTC, thibault-martinez approved these changes

2019-03-12 14:38 UTC, merged