cclient/serializer/json:get_neighbors - serialize response
iotaledger/entangled pull request #955
Opened 2019-03-13 08:40 UTC by HowJMay

#872 
implement API get_neighbors response serialization

implement neighbor_info_utarray_to_json_array()

2019-03-13 10:52 UTC, oopsmonk requested changes

2019-03-13 10:52 UTC, oopsmonk commented on cclient/serialization/json/helpers.c
> +  if (utarray_len(ut) > 0) {
check if `ut` is NULL.

2019-03-13 10:52 UTC, oopsmonk commented on cclient/serialization/json/tests/get_neighbors.c
> +  char_buffer_allocate(test_neighbors_neighbor1,
char_buffer_allocate is no need.

2019-03-13 10:52 UTC, oopsmonk commented on cclient/serialization/json/tests/get_neighbors.c
> +  char_buffer_allocate(test_neighbors_neighbor2,
ditto

2019-03-13 10:52 UTC, oopsmonk commented on cclient/serialization/json/get_neighbors.c
> +    len = strlen(json_text);
you can use `char_buffer_set` instead of `char_buffer_allocate`

2019-03-14 02:31 UTC, oopsmonk requested changes

2019-03-14 02:31 UTC, oopsmonk commented on cclient/serialization/json/helpers.c
> +retcode_t neighbor_info_utarray_to_json_array(UT_array const* const ut,
it should be a private method, move to `cclient/serialization/json/get_neighbors.c`

2019-03-14 02:31 UTC, oopsmonk commented on cclient/serialization/json/helpers.c
> +    return RC_CCLIENT_JSON_PARSE;
RC_NULL_PARAM

2019-03-14 02:36 UTC, oopsmonk requested changes

2019-03-14 02:36 UTC, oopsmonk commented on cclient/serialization/json/get_neighbors.c
> +  size_t len;
unused variable

2019-03-14 09:01 UTC, thibault-martinez requested changes

2019-03-14 09:01 UTC, thibault-martinez commented on cclient/serialization/json/get_neighbors.c
> +retcode_t neighbor_info_utarray_to_json_array(UT_array const *const ut,
Make it static ?

2019-03-14 09:01 UTC, thibault-martinez commented on cclient/serialization/json/get_neighbors.c
>    const char *req_text = "{\"command\":\"getNeighbors\"}";
const placement

2019-03-14 09:01 UTC, thibault-martinez commented on cclient/serialization/json/get_neighbors.c
> +  const char *json_text = NULL;
const placement

2019-03-14 14:45 UTC, thibault-martinez approved these changes

2019-03-15 02:40 UTC, oopsmonk approved these changes

2019-03-15 02:58 UTC, merged

2019-03-15 02:59 UTC, oopsmonk commented
@HowJMay thanks :)