implement get_tips response serialization
iotaledger/entangled pull request #969
Opened 2019-03-16 09:08 UTC by HowJMay

implement get_tips response serialization

implement hash243_stack_to_json_array()

2019-03-16 13:49 UTC, thibault-martinez commented
Hi @HowJMay Thanks again for the PR !
There seems to be memory leaks, could you have a look at the CI ?

2019-03-16 13:55 UTC, HowJMay commented
Sor my fault ! 
I'm gonna fix it now

2019-03-18 03:57 UTC, oopsmonk requested changes

2019-03-18 03:57 UTC, oopsmonk commented on cclient/serialization/json/helpers.c
> +                             cJSON_CreateString((const char*)trytes_out));
`char const*`

2019-03-18 03:57 UTC, oopsmonk commented on cclient/serialization/json/tests/get_tips.c
> +                                     (const tryte_t*)TEST_81_TRYTES_1,
ditto

2019-03-18 03:57 UTC, oopsmonk commented on cclient/serialization/json/tests/get_tips.c
> +                                     (const tryte_t*)TEST_81_TRYTES_2,
ditto

2019-03-18 03:57 UTC, oopsmonk commented on cclient/serialization/json/tests/get_tips.c
> +                                     (const tryte_t*)TEST_81_TRYTES_3,
ditto

2019-03-20 11:03 UTC, oopsmonk approved these changes

2019-03-20 11:04 UTC, merged